env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-plusplus: off
  semi:
    - error
    - always
  brace-style:
    - error
    - allman

